### ISSUE TITLE
Converting to lowercase?

### ISSUE THREAD

**Issue by jcayzac** [mathiasrw/rexreplace#1]
Hi,

Thanks for this super-useful tool I've been using a lot over the past months!

I'm currently facing an issue with the latest published version (2.2.3) where I can't get to have part of a match converted to lowercase:

```sh
rexreplace '^( *)m([A-Z])([a-zA-Z0-9_]*\b *)=' '"$1this." + ("$2".toLowerCase()) + "$3="' 'src/main/java/**/*.java' -J
```

Expected result would be something like

```diff
-     mFooBar    = 42;
+     this.fooBar    = 42;
```

However, I'm getting:

```diff
-     mFooBar    = 42;
+     this.FooBar    = 42;
```

…and `.toLowerCase()` has no effect.

Am I missing something?
Thanks!

**Comment by mathiasrw** [comment]
@jcayzac great to hear that you find it useful. 

I totally get the use case. 

The replacement is (at this present moment) only generate once - so what you are trying is not supported. 

I have added it to the top of [future ideas](https://github.com/mathiasrw/rexreplace/blob/master/README.md#future-ideas)

**Comment by jcayzac** [comment]
Thanks. I had to use Perl to get what I wanted this time, but looking forward to any improvement you bring to this little gem :)

**Comment by mathiasrw** [comment]
2.3.0 out now supporting the `j` flag. 

If you could test it out that would be awesome. Your original command should be something like

    rexreplace '^( *)m([A-Z])([a-zA-Z0-9_]*\b *)=' '$1+"this." + $2.toLowerCase() + $3 + "="' 'src/main/java/**/*.java' -J

**Comment by jcayzac** [comment]
Wow, you're fast!

I get this error with `2.3.1`:

```
undefined:1
$1 + "this." + $2.toLowerCase() + $3 + "="
^

ReferenceError: $1 is not defined
    at eval (eval at getFinalReplacement (/Users/bob/.nvm/versions/node/v6.9.1/lib/node_modules/rexreplace/build/ES6/rexreplace.cli.bundle.js:15467:22), <anonymous>:1:1)
    at getFinalReplacement (/Users/bob/.nvm/versions/node/v6.9.1/lib/node_modules/rexreplace/build/ES6/rexreplace.cli.bundle.js:15467:11)
    at module.exports (/Users/bob/.nvm/versions/node/v6.9.1/lib/node_modules/rexreplace/build/ES6/rexreplace.cli.bundle.js:15391:23)
    at Object.__dirname.93../core (/Users/bob/.nvm/versions/node/v6.9.1/lib/node_modules/rexreplace/build/ES6/rexreplace.cli.bundle.js:15375:1)
    at s (/Users/bob/.nvm/versions/node/v6.9.1/lib/node_modules/rexreplace/build/ES6/rexreplace.cli.bundle.js:1:316)
    at e (/Users/bob/.nvm/versions/node/v6.9.1/lib/node_modules/rexreplace/build/ES6/rexreplace.cli.bundle.js:1:487)
    at Object.<anonymous> (/Users/bob/.nvm/versions/node/v6.9.1/lib/node_modules/rexreplace/build/ES6/rexreplace.cli.bundle.js:1:505)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by mathiasrw** [comment]
Ahhhhaaaaa....

I forgot to change the `J` in the example to `j`. Woops...
